package student;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ramwell Tupas
 */

import java.io.File;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Records extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Records() {
        initComponents();
        tableUpdate();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private int selectedIndex;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtempaddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtempemail = new javax.swing.JTextField();
        txtempcontact = new javax.swing.JTextField();
        txtempgender = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtempstatus = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtempname = new javax.swing.JTextField();
        txtempbirthdate = new javax.swing.JTextField();
        txtempcourse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtempage = new javax.swing.JTextField();
        txtempbirthplace = new javax.swing.JTextField();
        previousBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Enrollment System");
        setName("dbUI"); // NOI18N
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(232, 211, 209));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("STUDENT RECORDS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Course", "Age", "Gender", "Civil Status", "Birthdate", "Birthplace", "Contact #", "Email Address", "Address"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(143, 35, 33));
        jButton1.setForeground(new java.awt.Color(232, 211, 209));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(143, 35, 33));
        jButton3.setForeground(new java.awt.Color(232, 211, 209));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(143, 35, 33));
        jButton2.setForeground(new java.awt.Color(232, 211, 209));
        jButton2.setText("Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtempaddress.setName("studentAddress"); // NOI18N

        jLabel11.setForeground(new java.awt.Color(232, 211, 209));
        jLabel11.setText("Email Address:");
        jLabel11.setName("contactNum"); // NOI18N

        jLabel7.setForeground(new java.awt.Color(232, 211, 209));
        jLabel7.setText("Contact #:");
        jLabel7.setName("contactNum"); // NOI18N

        txtempemail.setName("studentContact"); // NOI18N

        txtempcontact.setName("studentContact"); // NOI18N

        txtempgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        txtempgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempgenderActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(232, 211, 209));
        jLabel12.setText("Civil Status:");

        jLabel2.setForeground(new java.awt.Color(232, 211, 209));
        jLabel2.setText("Name:");

        txtempstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Legally Separated", "Widowed" }));

        jLabel3.setForeground(new java.awt.Color(232, 211, 209));
        jLabel3.setText("Age:");

        jLabel5.setForeground(new java.awt.Color(232, 211, 209));
        jLabel5.setText("Address:");

        jLabel1.setForeground(new java.awt.Color(232, 211, 209));
        jLabel1.setText("Gender:");

        jLabel6.setForeground(new java.awt.Color(232, 211, 209));
        jLabel6.setText("Course:");

        jLabel9.setForeground(new java.awt.Color(232, 211, 209));
        jLabel9.setText("Birthdate:");

        txtempname.setName("studentName"); // NOI18N
        txtempname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempnameActionPerformed(evt);
            }
        });

        txtempbirthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempbirthdateActionPerformed(evt);
            }
        });

        txtempcourse.setName("studentCourse"); // NOI18N

        jLabel10.setForeground(new java.awt.Color(232, 211, 209));
        jLabel10.setText("Birthplace:");

        txtempage.setName("studentYearSec"); // NOI18N

        previousBtn.setBackground(new java.awt.Color(143, 35, 33));
        previousBtn.setForeground(new java.awt.Color(232, 211, 209));
        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        nextBtn.setBackground(new java.awt.Color(143, 35, 33));
        nextBtn.setForeground(new java.awt.Color(232, 211, 209));
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(previousBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nextBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempname))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempcourse))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempaddress))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempcontact))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempemail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempgender, 0, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtempbirthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtempcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtempage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtempgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtempstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtempbirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtempbirthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtempcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtempemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtempaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(previousBtn)
                            .addComponent(nextBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void tableUpdate() {
        
        int c;
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String relativePath = "database/studentenrollment.accdb";
            String url = "jdbc:ucanaccess://" + new File(relativePath).getAbsolutePath();
            Connection con = DriverManager.getConnection(url);
            pst = con.prepareStatement("SELECT * from studentrecord");
            rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)jTable1.getModel();
            dft.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i = 1; i <= c; i++)
                {
                    v2.add(rs.getString("studentID"));
                    v2.add(rs.getString("studentName"));
                    v2.add(rs.getString("studentCourse"));
                    v2.add(rs.getString("studentAge"));
                    v2.add(rs.getString("studentGender"));
                    v2.add(rs.getString("studentStatus"));
                    v2.add(rs.getString("birthDate"));
                    v2.add(rs.getString("birthPlace"));
                    v2.add(rs.getString("studentContact"));
                    v2.add(rs.getString("studentEmail"));
                    v2.add(rs.getString("studentAddress"));
                }
                dft.addRow(v2);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentRecord.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());   
        
        int dialogueresult = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogueresult == JOptionPane.YES_NO_OPTION){
            try {
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                String relativePath = "database/studentenrollment.accdb";
                String url = "jdbc:ucanaccess://" + new File(relativePath).getAbsolutePath();
                Connection con = DriverManager.getConnection(url);
                pst = con.prepareStatement("DELETE from studentrecord WHERE studentID=?");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Deleted");
                txtempname.setText("");
                txtempname.requestFocus();
                tableUpdate();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Records.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Records.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        selectedIndex = jTable1.getSelectedRow();
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());   
        String name, course, age, gender, status, birthdate, birthplace, contact, email, address;
        int genderIndex = txtempgender.getSelectedIndex();
        int statusIndex = txtempstatus.getSelectedIndex();
        
        name = txtempname.getText();
        course = txtempcourse.getText();
        age = txtempage.getText();
        gender = txtempgender.getItemAt(genderIndex);
        status = txtempstatus.getItemAt(statusIndex);
        birthdate = txtempbirthdate.getText();
        birthplace = txtempbirthplace.getText();
        contact = txtempcontact.getText();
        email = txtempemail.getText();
        address = txtempaddress.getText();
        System.out.print(name); System.out.print(course); System.out.print(age);
        System.out.print(gender); System.out.print(status); System.out.print(birthdate);
        System.out.print(birthplace); System.out.print(contact); System.out.print(email);
        System.out.print(address);
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String relativePath = "database/studentenrollment.accdb";
            String url = "jdbc:ucanaccess://" + new File(relativePath).getAbsolutePath();
            Connection con = DriverManager.getConnection(url);

            // Check for duplicate email or contact
            String checkQuery = "SELECT * FROM studentrecord WHERE (studentEmail = ? OR studentContact = ?) AND studentID != ?";
            pst = con.prepareStatement(checkQuery);
            pst.setString(1, email);
            pst.setString(2, contact);
            pst.setInt(3, id);
            rs = pst.executeQuery();

            if (rs.next()) {
                // Email or contact already exists
                JOptionPane.showMessageDialog(this, "Email or Contact already exists!");
            } else {
                // Update the record
                String updateQuery = "UPDATE studentrecord SET studentName=?, studentCourse=?, studentAge=?, studentGender=?, studentStatus=?, birthDate=?, birthPlace=?, studentContact=?, studentEmail=?, studentAddress=? WHERE studentID=?";
                pst = con.prepareStatement(updateQuery);
                pst.setString(1, name);
                pst.setString(2, course);
                pst.setString(3, age);
                pst.setString(4, gender);
                pst.setString(5, status);
                pst.setString(6, birthdate);
                pst.setString(7, birthplace);
                pst.setString(8, contact);
                pst.setString(9, email);
                pst.setString(10, address);
                pst.setInt(11, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated");

                // Clear input fields
                txtempname.setText("");
                txtempcourse.setText("");
                txtempage.setText("");
                txtempgender.setSelectedIndex(0);
                txtempstatus.setSelectedIndex(0);
                txtempbirthdate.setText("");
                txtempbirthplace.setText("");
                txtempcontact.setText("");
                txtempemail.setText("");
                txtempaddress.setText("");
                txtempname.requestFocus();

                // Update the table
                tableUpdate();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentRecord.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentRecord.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                Logger.getLogger(StudentRecord.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        selectedIndex = jTable1.getSelectedRow();
        
        txtempname.setText(model.getValueAt(selectedIndex, 1).toString());
        txtempcourse.setText(model.getValueAt(selectedIndex, 2).toString());
        txtempage.setText(model.getValueAt(selectedIndex, 3).toString());
        txtempgender.setSelectedIndex(0);
        txtempstatus.setSelectedIndex(0);
        txtempbirthdate.setText(model.getValueAt(selectedIndex, 6).toString());
        txtempbirthplace.setText(model.getValueAt(selectedIndex, 7).toString());
        txtempcontact.setText(model.getValueAt(selectedIndex, 8).toString());
        txtempemail.setText(model.getValueAt(selectedIndex, 9).toString());
        txtempaddress.setText(model.getValueAt(selectedIndex, 10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtempgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempgenderActionPerformed

    private void txtempnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempnameActionPerformed

    private void txtempbirthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempbirthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempbirthdateActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        if (selectedIndex > 0) {
            selectedIndex--;
            jTable1.setRowSelectionInterval(selectedIndex, selectedIndex);
            updateFields();
        }
        
    }//GEN-LAST:event_previousBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        if (selectedIndex < model.getRowCount() - 1) {
            selectedIndex++;
            jTable1.setRowSelectionInterval(selectedIndex, selectedIndex);
            updateFields();
        }
        
    }//GEN-LAST:event_nextBtnActionPerformed
    
    private void updateFields(){
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        txtempname.setText(model.getValueAt(selectedIndex, 1).toString());
        txtempcourse.setText(model.getValueAt(selectedIndex, 2).toString());
        txtempage.setText(model.getValueAt(selectedIndex, 3).toString());
        txtempgender.setSelectedIndex(0);
        txtempstatus.setSelectedIndex(0);
        txtempbirthdate.setText(model.getValueAt(selectedIndex, 6).toString());
        txtempbirthplace.setText(model.getValueAt(selectedIndex, 7).toString());
        txtempcontact.setText(model.getValueAt(selectedIndex, 8).toString());
        txtempemail.setText(model.getValueAt(selectedIndex, 9).toString());
        txtempaddress.setText(model.getValueAt(selectedIndex, 10).toString());
    }
    
    private void display() {
        JFrame f = new JFrame();
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.add(this);
        f.pack();
        f.setExtendedState(f.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        f.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records().display();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JTextField txtempaddress;
    private javax.swing.JTextField txtempage;
    private javax.swing.JTextField txtempbirthdate;
    private javax.swing.JTextField txtempbirthplace;
    private javax.swing.JTextField txtempcontact;
    private javax.swing.JTextField txtempcourse;
    private javax.swing.JTextField txtempemail;
    private javax.swing.JComboBox<String> txtempgender;
    private javax.swing.JTextField txtempname;
    private javax.swing.JComboBox<String> txtempstatus;
    // End of variables declaration//GEN-END:variables
}
